apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kms-vault-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - apps
  resourceNames:
  - kms-vault-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.patoarvizu.dev
  resources:
  - kmsvaultsecrets
  - partialkmsvaultsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.patoarvizu.dev
  resources:
  - kmsvaultsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete