{{- if .Values.validatingWebhook.enabled }}
kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: kms-vault-validating-webhook
  {{- if .Values.validatingWebhook.certManager.injectSecret }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/kms-vault-validating-webhook
  {{- end }}
webhooks:
- name: kms-vault-validating-webhook.patoarvizu.dev
  rules:
  - apiGroups:
    - k8s.patoarvizu.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kmsvaultsecrets
    - partialkmsvaultsecrets
  failurePolicy: {{ .Values.validatingWebhook.failurePolicy }}
  sideEffects: None
  admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: {{ .Values.validatingWebhook.caBundle }}
    service:
      namespace: {{ .Release.Namespace }}
      name: kms-vault-validating-webhook
  namespaceSelector:
    matchExpressions:
    {{- range $i, $val := .Values.validatingWebhook.namespaceSelectorExpressions }}
    - key: {{ $val.key }}
      operator: {{ $val.operator }}
    {{- end -}}
{{- end }}